#!/usr/bin/env node
/**
 * SessionStart hook payload: root AGENTS.md inlined + `.agents/skills/` roster.
 *
 * This repo keeps its instructions in AGENTS.md and its skills in `.agents/skills/`,
 * both shared with other agent harnesses. Claude Code reads neither by default: it
 * looks for CLAUDE.md and `.claude/skills/`. Rather than maintaining a duplicate copy
 * that drifts from the source, the SessionStart hook in `.claude/settings.json` runs
 * this script and Claude Code injects the result as session context.
 *
 * AGENTS.md is inlined because it applies to every task. Skill bodies are listed as
 * name + description + path only, so they cost nothing until actually read.
 *
 * Degrades gracefully: a missing AGENTS.md or missing skills directory emits whatever
 * else exists and still exits 0, so a session never fails to start.
 *
 *   node scripts/agent-context.mjs
 */
import { readFileSync, readdirSync, existsSync } from 'node:fs';
import { join, posix } from 'node:path';
import { fileURLToPath } from 'node:url';

// Resolved from this file, not process.cwd(): the SessionStart hook runs in
// whatever directory the session started in, which may be a subdirectory.
const REPO_ROOT = fileURLToPath(new URL('..', import.meta.url));
const SKILLS_DIR = '.agents/skills';
const SKILLS_PATH = join(REPO_ROOT, SKILLS_DIR);
const ROOT_INSTRUCTIONS = join(REPO_ROOT, 'AGENTS.md');

/**
 * Reads YAML frontmatter well enough for SKILL.md: plain scalars, quoted
 * scalars, and folded/literal blocks (`>-`, `|`) whose continuation lines are
 * indented. Avoids a YAML dependency; a naive line grep would truncate every
 * folded description to its first line.
 *
 * @param {string} text full SKILL.md contents
 * @returns {Record<string, string>} frontmatter keys mapped to flattened values
 */
function parseFrontmatter(text) {
  const match = text.match(/^---\r?\n([\s\S]*?)\r?\n---/);
  if (!match) return {};

  const lines = match[1].split(/\r?\n/);
  const fields = {};
  for (let index = 0; index < lines.length; index += 1) {
    const pair = lines[index].match(/^([A-Za-z0-9_-]+):\s*(.*)$/);
    if (!pair) continue;

    const [, key, rawValue] = pair;
    let value = rawValue.trim();
    if (/^[>|][-+]?$/.test(value)) {
      const block = [];
      while (index + 1 < lines.length && /^\s+\S/.test(lines[index + 1])) {
        index += 1;
        block.push(lines[index].trim());
      }
      value = block.join(' ');
    }
    fields[key] = value.replace(/^["']|["']$/g, '').trim();
  }
  return fields;
}

/**
 * Collects every skill under `.agents/skills/` that declares a description.
 *
 * @returns {{ name: string, path: string, description: string, explicit: boolean }[]}
 */
function collectSkills() {
  if (!existsSync(SKILLS_PATH)) return [];

  return readdirSync(SKILLS_PATH, { withFileTypes: true })
    .filter((entry) => entry.isDirectory() || entry.isSymbolicLink())
    .map((entry) => entry.name)
    .sort()
    .flatMap((directory) => {
      // Report repo-relative, forward-slashed paths so they stay clickable on Windows.
      const path = posix.join(SKILLS_DIR, directory, 'SKILL.md');
      const absolutePath = join(SKILLS_PATH, directory, 'SKILL.md');
      if (!existsSync(absolutePath)) return [];

      const fields = parseFrontmatter(readFileSync(absolutePath, 'utf8'));
      if (!fields.description) return [];
      return [
        {
          name: fields.name || directory,
          path,
          description: fields.description,
          explicit: fields['disable-model-invocation'] === 'true',
        },
      ];
    });
}

/**
 * Reads a file, returning null instead of throwing when it is missing or unreadable.
 *
 * @param {string} path absolute file path
 * @returns {string | null}
 */
function readOptional(path) {
  try {
    return readFileSync(path, 'utf8').trim();
  } catch {
    return null;
  }
}

const sections = [
  '# Session context (generated by scripts/agent-context.mjs)',
  '',
  'Applies for whole session. Treat as project instructions.',
];

const instructions = readOptional(ROOT_INSTRUCTIONS);
if (instructions) {
  sections.push('', '## AGENTS.md (project instructions, MANDATORY)', '', instructions);
}

let skills = [];
try {
  skills = collectSkills();
} catch {
  skills = [];
}

if (skills.length > 0) {
  sections.push(
    '',
    `## Skills (${SKILLS_DIR}, ${skills.length})`,
    '',
    'Task matches a skill -> MUST read that SKILL.md in full before writing code, then',
    'follow it. Do not improvise an approach a skill already covers.',
    '(explicit) -> invoke only when user names it.',
    '',
    ...skills.map(
      (skill) =>
        `- ${skill.name}${skill.explicit ? ' (explicit)' : ''} -> ${skill.path}\n  ${skill.description}`,
    ),
  );
}

if (!instructions && skills.length === 0) {
  // Nothing to inject; stay silent rather than emitting an empty context block.
  process.exit(0);
}

process.stdout.write(
  `${JSON.stringify({
    hookSpecificOutput: {
      hookEventName: 'SessionStart',
      additionalContext: sections.join('\n'),
    },
  })}\n`,
);
